name: ghdl-yosys-plugin

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:

  synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Prepare
        run: make prepare
      - name: Verifying ghdl-yosys-plugin with several examples
        run: bash helpers/docker_run.sh make verify-ghdl-yosys
