name: ghdl-yosys-plugin

on:
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:

  synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Prepare
        run: make -C xilinx prepare
      - name: Verifying ghdl-yosys-plugin with examples from Xilinx
        run: bash helpers/docker_run.sh make -C xilinx verify-ghdl-yosys
