name: verify

on:
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:

  synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run:
          make prepare
      - name: Verifying ghdl against several examples
        run:
          bash helpers/docker_run.sh make verify-ghdl
      - name: Verifying ghdl-yosys-plugin against several examples
        run:
          bash helpers/docker_run.sh make verify-ghdl-yosys
      - name: Verifying yosys against several examples
        run:
          bash helpers/docker_run.sh make verify-yosys
