name: verify

on: push

#on:
#  schedule:
#    - cron: '0 0 * * 0'

jobs:

  synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          make prepare
          make -C xilinx prepare
          make -C FPGADesignElements
      - name: Verifying ghdl-yosys-plugin against Xilinx examples
        run:
          bash helpers/docker_run.sh make -C xilinx ghdl-yosys
      - name: Verifying yosys against Xilinx examples
        run:
          bash helpers/docker_run.sh make -C xilinx yosys-vivado
      - name: Verifying yosys against FPGADesignElements examples
        run:
          bash helpers/docker_run.sh make -C FPGADesignElements yosys-vivado
